#=========================================================================================#
# 备份中存储机器人信息的文件路径
robotInfo:
  filePath: "/am.ini"
#===========================================================================================#





#===========================================================================================#
#描述文件加载时，加载哪些文件信息
fileLoadSection:
  # defaultAction 决定在 prefix / suffix 都未命中时的默认行为：
  # allow=保留，ignore=忽略。
  # 以!开头的规则代表忽略，其他规则代表保留。
  # 前缀和后缀会同时参与匹配；如果同一个字符串同时命中保留和忽略规则，将直接报错。
  defaultAction: ignore
  prefix:
    - "/am.ini"
    - "/KRC/R1"
    - "!/Log Files"
    - "!/Registry"
    - "!/C"
  suffix:
#===========================================================================================#


#===========================================================================================#
#进行语法解析时，对那些文件进行解析
carInvokerParseSection:
  # defaultAction 决定在 prefix / suffix 都未命中时的默认行为：
  # allow=保留，ignore=忽略。
  # 以!开头的规则代表忽略，其他规则代表保留。
  # 前缀和后缀会同时参与匹配；如果同一个字符串同时命中保留和忽略规则，将直接报错。
  # 程序中已设计为大小写不敏感，因此这里也不区分大小写
  defaultAction: allow
  prefix:
    - "!P00"  # 不解析默认自带的P00模块
    - "!ServiceMain"                    #不解析 服务程序
    - "!waitSeg"                        #不解析 waitSeg
    - "!EndSeg"                         #不解析 endSeg
    - "!enterZone"                      #不解析 进干涉区
    - "!exitZone"                       #不解析 出干涉区
    - "!toolChange"                     #不解析 工具切换
    - "!checkTOOL"                      #不解析 工具检查
    - "!SGL_Changing"                   #不解析 SGL_Changing
    - "!taskComp"                       #不解析 工作完成宏程序
    - "!BAS"                            #不解析 库卡基础程序:BAS
    - "!SET_CD_PARAMS"                  #不解析 设置参数设置 后台程序
    - "!RESET_IO"                       #不解析 刷信号IO 程序
    - "!couple"                         #不解析 耦合程序
    - "!use_cd_params"                  #不解析 使用参数
    - "!sg_init"                        #不解析 自带的初始化程序
    - "!GUN1_Tipdress_DABAN"            #不解析 打板修磨
    - "!GUN1_TipChange_DABAN"           #不解析 打板换帽
    - "!GUN1_TipService"                #不解析 打板服务
    - "!Tip"                            #不解析 和电极帽相关的程序，如TipDress、TipChange等
  suffix:
    - "!finish"                         # 不解析 finish结尾的 程序，例如 serviceFinish、taskFinish等
    - "!dress"                          # 不解析 dress结尾的 程序
#===========================================================================================#
